area = ["Dolný Kubín", "Tvrdošín", "Bratislava", "Ružomberok"]
log_level = "info"
period = 1
include_description = false
# "Unknown", "Mild", "Moderate", "Severe", "Extreme"
min_severity = "mild"
notifications = true

_fetch_only_one_alert = true